version: "3"
services:
  backend:
    container_name: ${APP_NAME}-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST:-backend-db}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${APP_NAME}-strapi.loadbalancer.server.port=1337"
      - "traefik.http.routers.${APP_NAME}-strapi.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}-strapi.tls=true"
      - "traefik.http.routers.${APP_NAME}-strapi.tls.certresolver=cloudflare"
      - "traefik.http.routers.${APP_NAME}-strapi.rule=Host(`${APP_HOSTNAME_BACKEND}`)"
    networks:
      - traefik
      - strapi
    depends_on:
      - backend-db

  backend-db:
    container_name: ${APP_NAME}-backend-db
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - strapi

  frontend:
    container_name: ${APP_NAME}-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.${APP_NAME}-frontend.loadbalancer.server.port=4000"
      - "traefik.http.routers.${APP_NAME}-frontend.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}-frontend.tls=true"
      - "traefik.http.routers.${APP_NAME}-frontend.tls.certresolver=cloudflare"
      - "traefik.http.routers.${APP_NAME}-frontend.rule=Host(`${APP_HOSTNAME}`)"
    networks:
      - traefik
      - strapi

networks:
  traefik:
    external: true
  strapi:
    name: ${APP_NAME}-strapi-network
    driver: bridge
